# Each new term in the Fibonacci sequence is generated by adding the previous 
# two terms. By starting with 1 and 2, the first 10 terms will be:
#
#   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# Find the sum of all the even-valued terms in the sequence which do not 
# exceed four million.

a=1;b=2;c=0;d=[2]
while a < 4_000_000
  c=b;b=a+b;a=c
  next if b.odd?
  break if b > 4_000_000
  d << b
end
eval d.join '+'
